// Generates the new Drizzle-backed server.js
// Uses sql.raw() and computed JS values to avoid backtick conflicts
import { writeFileSync } from "fs";

const lines = [];
const L = (s) => lines.push(s);

L(`import express from 'express';`);
L(`import { createServer } from 'http';`);
L(`import { Server as SocketIOServer } from 'socket.io';`);
L(`import cors from 'cors';`);
L(`import { createHash } from 'crypto';`);
L(`import { GameEngine } from '../../../packages/shared/src/game/engine.ts';`);
L(`import { initDb } from './db/init.ts';`);
L(`import { db } from './db/index.ts';`);
L(`import {`);
L(`  users,`);
L(`  sessions,`);
L(`  rooms as roomsTable,`);
L(`  gachaItems as gachaItemsTable,`);
L(`  userCollection,`);
L(`  gameHistory as gameHistoryTable,`);
L(`} from './db/schema.ts';`);
L(`import { eq, and, gt, desc, sql } from 'drizzle-orm';`);
L(``);
L(`const HAND_NAMES = {`);
L(`  1: 'High Card', 2: 'One Pair', 3: 'Two Pair', 4: 'Three of a Kind',`);
L(`  5: 'Straight', 6: 'Flush', 7: 'Full House', 8: 'Four of a Kind',`);
L(`  9: 'Straight Flush', 10: 'Royal Flush',`);
L(`};`);
L(``);
L(`const CORS_ORIGINS = process.env.CORS_ORIGIN`);
L(`  ? process.env.CORS_ORIGIN.split(',').map(s => s.trim())`);
L(`  : ['http://localhost:5173', 'http://localhost:5174'];`);
L(``);
L(`const GACHA_ITEMS = [`);
L(`  { id: 'r001',   name: 'Classic Red',      type: 'card_skin',   rarity: 'R',   imageUrl: '/assets/gacha/r001.png',  description: 'A clean crimson card back.' },`);
L(`  { id: 'r002',   name: 'Ocean Blue',       type: 'card_skin',   rarity: 'R',   imageUrl: '/assets/gacha/r002.png',  description: 'Deep sea inspired design.' },`);
L(`  { id: 'r003',   name: 'Forest Night',     type: 'card_skin',   rarity: 'R',   imageUrl: '/assets/gacha/r003.png',  description: 'Dark emerald card back.' },`);
L(`  { id: 'r004',   name: 'Starfall',         type: 'card_skin',   rarity: 'R',   imageUrl: '/assets/gacha/r004.png',  description: 'Night sky with falling stars.' },`);
L(`  { id: 'r005',   name: 'Sandstorm',        type: 'card_skin',   rarity: 'R',   imageUrl: '/assets/gacha/r005.png',  description: 'Desert dunes in gold.' },`);
L(`  { id: 'sr001',  name: 'Kitsune Miko',     type: 'avatar',      rarity: 'SR',  imageUrl: '/assets/gacha/sr001.png', description: 'Fox shrine maiden with silver ears.' },`);
L(`  { id: 'sr002',  name: 'Shadow Assassin',  type: 'avatar',      rarity: 'SR',  imageUrl: '/assets/gacha/sr002.png', description: 'Masked figure with dark cape.' },`);
L(`  { id: 'sr003',  name: 'Sunlit Idol',      type: 'avatar',      rarity: 'SR',  imageUrl: '/assets/gacha/sr003.png', description: 'Radiant idol in golden outfit.' },`);
L(`  { id: 'sr004',  name: 'Thunder Ronin',    type: 'avatar',      rarity: 'SR',  imageUrl: '/assets/gacha/sr004.png', description: 'Storm-wielding samurai.' },`);
L(`  { id: 'ssr001', name: 'Celestial Dragon', type: 'table_theme', rarity: 'SSR', imageUrl: '/assets/gacha/ssr001.png',description: 'Legendary dragon felt with starlight chips.' },`);
L(`  { id: 'ssr002', name: 'Void Phoenix',     type: 'avatar',      rarity: 'SSR', imageUrl: '/assets/gacha/ssr002.png',description: 'A reborn phoenix emerging from the void.' },`);
L(`  { id: 'ssr003', name: 'Sakura Storm',     type: 'table_theme', rarity: 'SSR', imageUrl: '/assets/gacha/ssr003.png',description: 'Cherry blossom petals swirl around the table.' },`);
L(`];`);
L(``);
L(`const RATES       = { R: 0.85, SR: 0.12, SSR: 0.03 };`);
L(`const PITY_SR     = 10;`);
L(`const PITY_SSR    = 90;`);
L(`const SINGLE_COST = 150;`);
L(`const TEN_COST    = 1350;`);
L(``);
L(`const app        = express();`);
L(`const httpServer = createServer(app);`);
L(`const io         = new SocketIOServer(httpServer, {`);
L(`  cors: { origin: CORS_ORIGINS, credentials: true },`);
L(`  transports: ['websocket', 'polling'],`);
L(`});`);
L(`app.use(cors({ origin: CORS_ORIGINS, credentials: true }));`);
L(`app.use(express.json());`);
L(`app.get('/health', (_req, res) => res.json({ status: 'ok' }));`);
L(``);
L(`function genId()    { return Math.random().toString(36).substring(2, 14); }`);
L(`function genToken() { return genId() + genId(); }`);
L(`const hashPassword = (pass) =>`);
L(`  createHash('sha256').update(pass + 'poker-gacha-dev-salt').digest('hex');`);
L(``);
L(`function getTokenFromReq(req) {`);
L(`  const raw = req.headers.cookie || '';`);
L(`  for (const part of raw.split(';')) {`);
L(`    const [k, v] = part.trim().split('=');`);
L(`    if (k === 'session_token') return decodeURIComponent(v ?? '');`);
L(`  }`);
L(`  return null;`);
L(`}`);
L(``);
L(`async function getUserFromReq(req) {`);
L(`  const token = getTokenFromReq(req);`);
L(`  if (!token) return null;`);
L(`  const [session] = await db.select().from(sessions)`);
L(`    .where(and(eq(sessions.token, token), gt(sessions.expiresAt, new Date())))`);
L(`    .limit(1);`);
L(`  if (!session) return null;`);
L(`  const [user] = await db.select().from(users).where(eq(users.id, session.userId)).limit(1);`);
L(`  return user ?? null;`);
L(`}`);
L(``);
L(`const gameRooms = new Map();`);
L(``);
L(`function getPublicState(state) {`);
L(`  return { ...state, players: state.players.map(p => ({ ...p, cards: [] })) };`);
L(`}`);
L(``);
L(`async function seedGachaItems() {`);
L(`  for (const item of GACHA_ITEMS) {`);
L(`    await db.insert(gachaItemsTable).values(item).onConflictDoNothing();`);
L(`  }`);
L(`}`);
L(``);
L(`// ─── Auth ────────────────────────────────────────────────────────────────────`);
L(``);
L(`app.post('/api/auth/register', async (req, res) => {`);
L(`  try {`);
L(`    const { username, email, password } = req.body;`);
L(`    if (!username || !email || !password)`);
L(`      return res.status(400).json({ error: { code: 'VALIDATION', message: 'Missing fields' } });`);
L(`    if (username.length < 3)`);
L(`      return res.status(400).json({ error: { code: 'VALIDATION', message: 'Username must be at least 3 characters' } });`);
L(`    if (password.length < 6)`);
L(`      return res.status(400).json({ error: { code: 'VALIDATION', message: 'Password must be at least 6 characters' } });`);
L(`    const existing = await db.select({ id: users.id }).from(users).where(eq(users.email, email)).limit(1);`);
L(`    if (existing.length > 0)`);
L(`      return res.status(409).json({ error: { code: 'USER_EXISTS', message: 'User already exists' } });`);
L(`    const [user] = await db.insert(users)`);
L(`      .values({ username, email, passwordHash: hashPassword(password) })`);
L(`      .returning();`);
L(`    const token = genToken();`);
L(`    const expiresAt = new Date(Date.now() + 7 * 24 * 3600 * 1000);`);
L(`    await db.insert(sessions).values({ id: genId(), token, userId: user.id, expiresAt });`);
L(`    res.cookie('session_token', token, { httpOnly: true, sameSite: 'lax', maxAge: 7 * 24 * 3600 * 1000 });`);
L(`    const { passwordHash: _ph, ...safeUser } = user;`);
L(`    res.json({ user: safeUser, session: { token } });`);
L(`  } catch (err) {`);
L(`    console.error('Register error:', err);`);
L(`    res.status(500).json({ error: { code: 'SERVER_ERROR', message: 'Server error' } });`);
L(`  }`);
L(`});`);
L(``);
L(`app.post('/api/auth/login', async (req, res) => {`);
L(`  try {`);
L(`    const { email, password } = req.body;`);
L(`    const [user] = await db.select().from(users).where(eq(users.email, email)).limit(1);`);
L(`    if (!user || user.passwordHash !== hashPassword(password))`);
L(`      return res.status(401).json({ error: { code: 'INVALID_CREDENTIALS', message: 'Invalid email or password' } });`);
L(`    const token = genToken();`);
L(`    const expiresAt = new Date(Date.now() + 7 * 24 * 3600 * 1000);`);
L(`    await db.insert(sessions).values({ id: genId(), token, userId: user.id, expiresAt });`);
L(`    res.cookie('session_token', token, { httpOnly: true, sameSite: 'lax', maxAge: 7 * 24 * 3600 * 1000 });`);
L(`    const { passwordHash: _ph, ...safeUser } = user;`);
L(`    res.json({ user: safeUser, session: { token } });`);
L(`  } catch (err) {`);
L(`    console.error('Login error:', err);`);
L(`    res.status(500).json({ error: { code: 'SERVER_ERROR', message: 'Server error' } });`);
L(`  }`);
L(`});`);
L(``);
L(`app.post('/api/auth/logout', async (req, res) => {`);
L(`  try {`);
L(`    const token = getTokenFromReq(req);`);
L(`    if (token) await db.delete(sessions).where(eq(sessions.token, token));`);
L(`  } catch { /* best-effort */ }`);
L(`  res.clearCookie('session_token');`);
L(`  res.json({ success: true });`);
L(`});`);
L(``);
L(`app.get('/api/auth/me', async (req, res) => {`);
L(`  try {`);
L(`    const user = await getUserFromReq(req);`);
L(`    if (!user) return res.status(401).json({ error: { code: 'UNAUTHORIZED', message: 'Unauthorized' } });`);
L(`    let dailyReward = null;`);
L(`    const today = new Date().toLocaleDateString('en-CA');`);
L(`    if (user.lastDailyReward !== today) {`);
L(`      await db.update(users)`);
L(`        .set({ chips: user.chips + 200, lastDailyReward: today })`);
L(`        .where(eq(users.id, user.id));`);
L(`      user.chips += 200;`);
L(`      dailyReward = { chips: 200 };`);
L(`    }`);
L(`    const { passwordHash: _ph, ...safeUser } = user;`);
L(`    res.json({ user: safeUser, dailyReward });`);
L(`  } catch (err) {`);
L(`    console.error('Me error:', err);`);
L(`    res.status(500).json({ error: { code: 'SERVER_ERROR', message: 'Server error' } });`);
L(`  }`);
L(`});`);
L(``);
L(`// ─── Rooms ────────────────────────────────────────────────────────────────────`);
L(``);
L(`app.get('/api/rooms', async (_req, res) => {`);
L(`  try {`);
L(`    const waiting = await db.select().from(roomsTable).where(eq(roomsTable.status, 'waiting'));`);
L(`    res.json(waiting.map(r => ({`);
L(`      ...r,`);
L(`      createdAt: r.createdAt.toISOString(),`);
L(`      playerCount: gameRooms.get(r.id)?.socketMap.size ?? 0,`);
L(`    })));`);
L(`  } catch (err) {`);
L(`    console.error('Rooms list error:', err);`);
L(`    res.status(500).json({ error: { code: 'SERVER_ERROR', message: 'Server error' } });`);
L(`  }`);
L(`});`);
L(``);
L(`app.post('/api/rooms', async (req, res) => {`);
L(`  try {`);
L(`    const user = await getUserFromReq(req);`);
L(`    if (!user) return res.status(401).json({ error: { code: 'UNAUTHORIZED', message: 'Unauthorized' } });`);
L(`    const { name, maxPlayers = 6, minBet = 10 } = req.body;`);
L(`    if (!name || name.length < 3)`);
L(`      return res.status(400).json({ error: { code: 'VALIDATION', message: 'Room name must be at least 3 characters' } });`);
L(`    const [room] = await db.insert(roomsTable)`);
L(`      .values({ name, hostId: user.id, maxPlayers, minBet })`);
L(`      .returning();`);
L(`    res.json({ ...room, createdAt: room.createdAt.toISOString(), playerCount: 0 });`);
L(`  } catch (err) {`);
L(`    console.error('Create room error:', err);`);
L(`    res.status(500).json({ error: { code: 'SERVER_ERROR', message: 'Server error' } });`);
L(`  }`);
L(`});`);
L(``);
L(`app.get('/api/rooms/:id', async (req, res) => {`);
L(`  try {`);
L(`    const [room] = await db.select().from(roomsTable).where(eq(roomsTable.id, req.params.id)).limit(1);`);
L(`    if (!room) return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Room not found' } });`);
L(`    res.json({ ...room, createdAt: room.createdAt.toISOString() });`);
L(`  } catch (err) {`);
L(`    res.status(500).json({ error: { code: 'SERVER_ERROR', message: 'Server error' } });`);
L(`  }`);
L(`});`);
L(``);
L(`app.delete('/api/rooms/:id', async (req, res) => {`);
L(`  try {`);
L(`    const user = await getUserFromReq(req);`);
L(`    if (!user) return res.status(401).json({ error: { code: 'UNAUTHORIZED', message: 'Unauthorized' } });`);
L(`    const [room] = await db.select().from(roomsTable).where(eq(roomsTable.id, req.params.id)).limit(1);`);
L(`    if (!room) return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Room not found' } });`);
L(`    if (room.hostId !== user.id)`);
L(`      return res.status(403).json({ error: { code: 'FORBIDDEN', message: 'Only the host can delete this room' } });`);
L(`    await db.delete(roomsTable).where(eq(roomsTable.id, req.params.id));`);
L(`    res.json({ success: true });`);
L(`  } catch (err) {`);
L(`    res.status(500).json({ error: { code: 'SERVER_ERROR', message: 'Server error' } });`);
L(`  }`);
L(`});`);
L(``);
L(`// ─── Socket.IO ────────────────────────────────────────────────────────────────`);
L(``);
L(`io.on('connection', async (socket) => {`);
L(`  const auth = socket.handshake.auth || {};`);
L(`  let user;`);
L(`  if (auth.mockUser) {`);
L(`    user = auth.mockUser;`);
L(`  } else if (auth.userId) {`);
L(`    const [found] = await db.select().from(users).where(eq(users.id, auth.userId)).limit(1);`);
L(`    user = found ?? { id: auth.userId, username: auth.username || 'Player_' + auth.userId.slice(0, 5), chips: auth.chips || 1000 };`);
L(`  }`);
L(`  if (!user) user = { id: socket.id, username: 'Guest_' + socket.id.slice(0, 5), chips: 1000 };`);
L(`  socket.data.user = user;`);
L(`  console.log('Connected:', user.username, '(' + socket.id + ')');`);
L(``);
L(`  socket.on('room:join', (roomId) => {`);
L(`    socket.join(roomId);`);
L(`    socket.data.roomId = roomId;`);
L(`    if (!gameRooms.has(roomId)) {`);
L(`      gameRooms.set(roomId, { engine: null, state: null, readySet: new Set(), socketMap: new Map(), dealerIndex: 0, roundNumber: 0 });`);
L(`    }`);
L(`    const room = gameRooms.get(roomId);`);
L(`    room.socketMap.set(user.id, socket.id);`);
L(`    if (room.state) {`);
L(`      socket.emit('game:stateUpdate', getPublicState(room.state));`);
L(`      const privateCards = room.state.players.find(p => p.id === user.id)?.cards ?? [];`);
L(`      if (privateCards.length) socket.emit('game:yourCards', privateCards);`);
L(`    }`);
L(`    console.log(user.username, 'joined room', roomId);`);
L(`  });`);
L(``);
L(`  socket.on('room:ready', async () => {`);
L(`    const roomId = socket.data.roomId;`);
L(`    if (!roomId) return;`);
L(`    const room = gameRooms.get(roomId);`);
L(`    if (!room) return;`);
L(`    room.readySet.add(user.id);`);
L(`    if (room.readySet.size >= 2) {`);
L(`      const socketsInRoom = await io.in(roomId).fetchSockets();`);
L(`      const socketByUserId = new Map(socketsInRoom.map(s => [s.data.user?.id, s]));`);
L(`      const players = [...room.readySet]`);
L(`        .map(uid => {`);
L(`          const s = socketByUserId.get(uid);`);
L(`          if (!s) return null;`);
L(`          return { id: s.data.user.id, username: s.data.user.username, chips: s.data.user.chips ?? 1000 };`);
L(`        })`);
L(`        .filter(p => p && p.chips > 0);`);
L(`      if (players.length < 2) return;`);
L(`      const sessionKey = players.map(p => p.id).sort().join(',');`);
L(`      if (room.currentSessionKey === sessionKey && room.state && room.state.phase !== 'showdown') return;`);
L(`      room.currentSessionKey = sessionKey;`);
L(`      const engine = new GameEngine(players, 10, 20);`);
L(`      const state  = engine.startGame(room.dealerIndex);`);
L(`      room.engine  = engine;`);
L(`      room.state   = state;`);
L(`      room.roundNumber = (room.roundNumber || 0) + 1;`);
L(`      room.readySet.clear();`);
L(`      await db.update(roomsTable).set({ status: 'playing' }).where(eq(roomsTable.id, roomId)).catch(() => {});`);
L(`      console.log('Game started in room', roomId, 'with', players.length, 'players');`);
L(`      io.to(roomId).emit('game:started');`);
L(`      io.to(roomId).emit('game:stateUpdate', getPublicState(state));`);
L(`      for (const s of socketsInRoom) {`);
L(`        const pid = s.data.user.id;`);
L(`        const privateCards = state.players.find(p => p.id === pid)?.cards ?? [];`);
L(`        s.emit('game:yourCards', privateCards);`);
L(`      }`);
L(`      if (state.activePlayerId) io.to(roomId).emit('game:playerTurn', state.activePlayerId, 30000);`);
L(`    }`);
L(`  });`);
L(``);
L(`  socket.on('game:action', async (action) => {`);
L(`    const roomId = socket.data.roomId;`);
L(`    if (!roomId) return;`);
L(`    const room = gameRooms.get(roomId);`);
L(`    if (!room || !room.engine || !room.state) return;`);
L(`    try {`);
L(`      room.state = room.engine.applyAction(room.state, user.id, action);`);
L(`      const newState = room.state;`);
L(`      if (newState.phase === 'showdown') {`);
L(`        io.to(roomId).emit('game:stateUpdate', newState);`);
L(`        let winners = [];`);
L(`        const handDescriptions = {};`);
L(`        try {`);
L(`          const result = room.engine.resolveShowdown(newState);`);
L(`          if (result) {`);
L(`            winners = Array.from(result.payouts.entries()).map(([playerId, amount]) => ({ playerId, amount }));`);
L(`            for (const [pid, hr] of result.handResults.entries()) {`);
L(`              handDescriptions[pid] = HAND_NAMES[hr.rank] ?? 'Unknown';`);
L(`            }`);
L(`          }`);
L(`        } catch (resolveErr) {`);
L(`          console.error('Resolve error:', resolveErr.message);`);
L(`          const lastStanding = newState.players.find(p => p.status !== 'folded');`);
L(`          if (lastStanding) winners = [{ playerId: lastStanding.id, amount: newState.pot }];`);
L(`        }`);
L(`        const socketsInRoom = await io.in(roomId).fetchSockets();`);
L(`        const chipUpdates   = {};`);
L(`        for (const p of newState.players) {`);
L(`          const payout      = winners.find(w => w.playerId === p.id)?.amount ?? 0;`);
L(`          const finalChips  = p.chips + payout;`);
L(`          chipUpdates[p.id] = finalChips;`);
L(`          const s = socketsInRoom.find(s => s.data.user?.id === p.id);`);
L(`          if (s) s.data.user.chips = finalChips;`);
L(`          // Fetch current DB user stats, then persist updated values`);
L(`          db.select({ handsPlayed: users.handsPlayed, wins: users.wins })`);
L(`            .from(users).where(eq(users.id, p.id)).limit(1)`);
L(`            .then(([dbUser]) => {`);
L(`              if (!dbUser) return;`);
L(`              const isWinner = payout > 0;`);
L(`              return db.update(users).set({`);
L(`                chips: finalChips,`);
L(`                handsPlayed: dbUser.handsPlayed + 1,`);
L(`                ...(isWinner ? { wins: dbUser.wins + 1 } : {}),`);
L(`              }).where(eq(users.id, p.id));`);
L(`            })`);
L(`            .catch(err => console.error('Chip update error:', err));`);
L(`        }`);
L(`        room.dealerIndex = (room.dealerIndex + 1) % newState.players.length;`);
L(`        io.to(roomId).emit('game:ended', { winners, handDescriptions, chipUpdates });`);
L(`        db.insert(gameHistoryTable).values({`);
L(`          roomId,`);
L(`          roundNumber: room.roundNumber,`);
L(`          pot: newState.pot,`);
L(`          winners,`);
L(`          playerSummary: newState.players.map(p => ({`);
L(`            id: p.id,`);
L(`            username: p.username ?? p.id,`);
L(`            finalChips: chipUpdates[p.id] ?? p.chips,`);
L(`            status: p.status,`);
L(`          })),`);
L(`          handDescriptions,`);
L(`        }).catch(err => console.error('History save error:', err));`);
L(`        await db.update(roomsTable).set({ status: 'waiting' }).where(eq(roomsTable.id, roomId)).catch(() => {});`);
L(`        room.engine = null;`);
L(`        room.state  = null;`);
L(`        return;`);
L(`      }`);
L(`      io.to(roomId).emit('game:stateUpdate', getPublicState(newState));`);
L(`      if (newState.activePlayerId) io.to(roomId).emit('game:playerTurn', newState.activePlayerId, 30000);`);
L(`    } catch (err) {`);
L(`      console.error('Action error:', err.message);`);
L(`      socket.emit('game:error', err.message);`);
L(`    }`);
L(`  });`);
L(``);
L(`  socket.on('game:chat', (message) => {`);
L(`    const roomId = socket.data.roomId;`);
L(`    if (!roomId) return;`);
L(`    io.to(roomId).emit('game:chatMessage', user.id, user.username, message);`);
L(`  });`);
L(``);
L(`  socket.on('room:leave', () => {`);
L(`    const roomId = socket.data.roomId;`);
L(`    if (!roomId) return;`);
L(`    socket.leave(roomId);`);
L(`    const room = gameRooms.get(roomId);`);
L(`    if (room) room.socketMap.delete(user.id);`);
L(`    socket.data.roomId = null;`);
L(`  });`);
L(``);
L(`  socket.on('disconnect', () => {`);
L(`    console.log('Disconnected:', user.username);`);
L(`    const roomId = socket.data.roomId;`);
L(`    if (roomId) {`);
L(`      const room = gameRooms.get(roomId);`);
L(`      if (room) room.socketMap.delete(user.id);`);
L(`    }`);
L(`  });`);
L(`});`);
L(``);
L(`// ─── Gacha ────────────────────────────────────────────────────────────────────`);
L(``);
L(`function rollRarity(pityCountSR, pityCountSSR) {`);
L(`  if (pityCountSSR >= PITY_SSR - 1) return 'SSR';`);
L(`  if (pityCountSR  >= PITY_SR  - 1) return 'SR';`);
L(`  const r = Math.random();`);
L(`  if (r < RATES.SSR)              return 'SSR';`);
L(`  if (r < RATES.SSR + RATES.SR)  return 'SR';`);
L(`  return 'R';`);
L(`}`);
L(``);
L(`function pickItem(rarity, ownedIds) {`);
L(`  const pool = GACHA_ITEMS.filter(i => i.rarity === rarity);`);
L(`  if (rarity === 'SSR') {`);
L(`    const unowned = pool.filter(i => !ownedIds.has(i.id));`);
L(`    if (unowned.length > 0) return unowned[Math.floor(Math.random() * unowned.length)];`);
L(`  }`);
L(`  return pool[Math.floor(Math.random() * pool.length)];`);
L(`}`);
L(``);
L(`app.get('/api/gacha/banners', (_req, res) => {`);
L(`  res.json([{`);
L(`    id: 'standard',`);
L(`    name: 'Standard Banner',`);
L(`    description: 'All items available. Pity resets every 90 pulls.',`);
L(`    featuredItem: GACHA_ITEMS.find(i => i.rarity === 'SSR'),`);
L(`    rates: RATES,`);
L(`  }]);`);
L(`});`);
L(``);
L(`app.get('/api/gacha/rates/:bannerId', (_req, res) => {`);
L(`  res.json({ rates: RATES, pitySR: PITY_SR, pitySSR: PITY_SSR, singleCost: SINGLE_COST, tenCost: TEN_COST });`);
L(`});`);
L(``);
L(`app.post('/api/gacha/pull', async (req, res) => {`);
L(`  try {`);
L(`    const user = await getUserFromReq(req);`);
L(`    if (!user) return res.status(401).json({ error: { code: 'UNAUTHORIZED', message: 'Unauthorized' } });`);
L(`    const count = req.body?.count === 10 ? 10 : 1;`);
L(`    const cost  = count === 10 ? TEN_COST : SINGLE_COST;`);
L(`    if (user.chips < cost)`);
L(`      return res.status(400).json({ error: { code: 'GACHA_ERROR', message: 'Not enough chips' } });`);
L(`    const ownedRows = await db.select({ itemId: userCollection.itemId }).from(userCollection).where(eq(userCollection.userId, user.id));`);
L(`    const ownedIds = new Set(ownedRows.map(r => r.itemId));`);
L(`    let { pityCountSR, pityCountSSR } = user;`);
L(`    const results = [];`);
L(`    for (let i = 0; i < count; i++) {`);
L(`      const rarity = rollRarity(pityCountSR, pityCountSSR);`);
L(`      if (rarity === 'SSR')     { pityCountSR = 0; pityCountSSR = 0; }`);
L(`      else if (rarity === 'SR') { pityCountSR = 0; pityCountSSR += 1; }`);
L(`      else                      { pityCountSR += 1; pityCountSSR += 1; }`);
L(`      const item = pickItem(rarity, ownedIds);`);
L(`      ownedIds.add(item.id);`);
L(`      await db.insert(userCollection).values({ userId: user.id, itemId: item.id }).onConflictDoNothing();`);
L(`      results.push({ ...item, isNew: true });`);
L(`    }`);
L(`    await db.update(users).set({ chips: user.chips - cost, pityCountSR, pityCountSSR }).where(eq(users.id, user.id));`);
L(`    res.json({ items: results, chips: user.chips - cost });`);
L(`  } catch (err) {`);
L(`    console.error('Gacha pull error:', err);`);
L(`    res.status(500).json({ error: { code: 'SERVER_ERROR', message: 'Server error' } });`);
L(`  }`);
L(`});`);
L(``);
L(`// ─── Collection ───────────────────────────────────────────────────────────────`);
L(``);
L(`app.get('/api/collection', async (req, res) => {`);
L(`  try {`);
L(`    const user = await getUserFromReq(req);`);
L(`    if (!user) return res.status(401).json({ error: { code: 'UNAUTHORIZED', message: 'Unauthorized' } });`);
L(`    const rows = await db`);
L(`      .select({`);
L(`        id: gachaItemsTable.id,`);
L(`        name: gachaItemsTable.name,`);
L(`        type: gachaItemsTable.type,`);
L(`        rarity: gachaItemsTable.rarity,`);
L(`        imageUrl: gachaItemsTable.imageUrl,`);
L(`        description: gachaItemsTable.description,`);
L(`        isEquipped: userCollection.isEquipped,`);
L(`      })`);
L(`      .from(userCollection)`);
L(`      .innerJoin(gachaItemsTable, eq(userCollection.itemId, gachaItemsTable.id))`);
L(`      .where(eq(userCollection.userId, user.id));`);
L(`    const equipped = rows.find(r => r.isEquipped);`);
L(`    res.json({ items: rows, equippedCardSkin: equipped?.id ?? null });`);
L(`  } catch (err) {`);
L(`    console.error('Collection list error:', err);`);
L(`    res.status(500).json({ error: { code: 'SERVER_ERROR', message: 'Server error' } });`);
L(`  }`);
L(`});`);
L(``);
L(`app.patch('/api/collection/:itemId/equip', async (req, res) => {`);
L(`  try {`);
L(`    const user = await getUserFromReq(req);`);
L(`    if (!user) return res.status(401).json({ error: { code: 'UNAUTHORIZED', message: 'Unauthorized' } });`);
L(`    const { itemId } = req.params;`);
L(`    const [row] = await db.select().from(userCollection)`);
L(`      .where(and(eq(userCollection.userId, user.id), eq(userCollection.itemId, itemId)))`);
L(`      .limit(1);`);
L(`    if (!row) return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Item not in collection' } });`);
L(`    const item = GACHA_ITEMS.find(i => i.id === itemId);`);
L(`    if (!item || item.type !== 'card_skin')`);
L(`      return res.status(400).json({ error: { code: 'INVALID', message: 'Only card_skin items can be equipped' } });`);
L(`    const wasEquipped = row.isEquipped;`);
L(`    await db.update(userCollection).set({ isEquipped: false }).where(eq(userCollection.userId, user.id));`);
L(`    if (!wasEquipped) {`);
L(`      await db.update(userCollection).set({ isEquipped: true })`);
L(`        .where(and(eq(userCollection.userId, user.id), eq(userCollection.itemId, itemId)));`);
L(`    }`);
L(`    res.json({ equipped: !wasEquipped, itemId, equippedCardSkin: wasEquipped ? null : itemId });`);
L(`  } catch (err) {`);
L(`    console.error('Equip error:', err);`);
L(`    res.status(500).json({ error: { code: 'SERVER_ERROR', message: 'Server error' } });`);
L(`  }`);
L(`});`);
L(``);
L(`// ─── History ──────────────────────────────────────────────────────────────────`);
L(``);
L(`app.get('/api/history', async (_req, res) => {`);
L(`  try {`);
L(`    const history = await db.select().from(gameHistoryTable)`);
L(`      .orderBy(desc(gameHistoryTable.playedAt)).limit(50);`);
L(`    res.json({ history });`);
L(`  } catch (err) {`);
L(`    res.status(500).json({ error: { code: 'SERVER_ERROR', message: 'Server error' } });`);
L(`  }`);
L(`});`);
L(``);
L(`app.get('/api/history/:id', async (req, res) => {`);
L(`  try {`);
L(`    const [entry] = await db.select().from(gameHistoryTable)`);
L(`      .where(eq(gameHistoryTable.id, req.params.id)).limit(1);`);
L(`    if (!entry) return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Game not found' } });`);
L(`    res.json(entry);`);
L(`  } catch (err) {`);
L(`    res.status(500).json({ error: { code: 'SERVER_ERROR', message: 'Server error' } });`);
L(`  }`);
L(`});`);
L(``);
L(`// ─── Leaderboard + Profile ────────────────────────────────────────────────────`);
L(``);
L(`app.get('/api/leaderboard', async (_req, res) => {`);
L(`  try {`);
L(`    const leaderboard = await db`);
L(`      .select({ id: users.id, username: users.username, chips: users.chips, wins: users.wins, handsPlayed: users.handsPlayed })`);
L(`      .from(users).orderBy(desc(users.chips)).limit(50);`);
L(`    res.json({ leaderboard });`);
L(`  } catch (err) {`);
L(`    res.status(500).json({ error: { code: 'SERVER_ERROR', message: 'Server error' } });`);
L(`  }`);
L(`});`);
L(``);
L(`app.get('/api/users/:id', async (req, res) => {`);
L(`  try {`);
L(`    const [target] = await db.select().from(users).where(eq(users.id, req.params.id)).limit(1);`);
L(`    if (!target) return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'User not found' } });`);
L(`    const collRows = await db.select({ c: sql.raw('count(*)') })`);
L(`      .from(userCollection).where(eq(userCollection.userId, target.id));`);
L(`    const collectionCount = Number(collRows[0]?.c ?? 0);`);
L(`    res.json({`);
L(`      user: { id: target.id, username: target.username, chips: target.chips, avatarUrl: target.avatarUrl ?? null },`);
L(`      stats: { wins: target.wins, handsPlayed: target.handsPlayed, collectionCount },`);
L(`    });`);
L(`  } catch (err) {`);
L(`    res.status(500).json({ error: { code: 'SERVER_ERROR', message: 'Server error' } });`);
L(`  }`);
L(`});`);
L(``);
L(`// ─── Start ────────────────────────────────────────────────────────────────────`);
L(``);
L(`async function startServer() {`);
L(`  await initDb();`);
L(`  await seedGachaItems();`);
L(`  const PORT = process.env.PORT || 3000;`);
L(`  httpServer.listen(PORT, () => {`);
L(`    console.log('Poker Backend running on port ' + PORT);`);
L(`    console.log('Socket.IO ready');`);
L(`  });`);
L(`}`);
L(``);
L(`startServer().catch(err => {`);
L(`  console.error('Failed to start server:', err);`);
L(`  process.exit(1);`);
L(`});`);

writeFileSync("./src/server.js", lines.join("\n"), "utf8");
console.log("✅ server.js written with", lines.length, "lines");
