'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { bannerVersionSchema, pullReceiptSchema, resultSchema, type PullReceipt, type PullRequest } from '@poker/contracts';
import { apiGet } from '../../lib/api';
import { economyMutation } from '../../lib/economy-api';
import { SessionBoundary, useSession } from '../auth/SessionBoundary';
import { useWallet } from '../wallet/useWallet';
import { useAccountSync } from '../collection/useAccountSync';
import { clearPendingPull, readPendingPull, savePendingPull } from './pendingPull';
import { PullReveal } from './PullReveal';

const bannerResponse = resultSchema(bannerVersionSchema);
const receiptResponse = resultSchema(pullReceiptSchema);
const definitive = new Set(['INVALID_REQUEST', 'INSUFFICIENT_TICKETS', 'STALE_BANNER', 'COMMAND_CONFLICT']);

export function Banner() {
  const { session, refresh } = useSession();
  const accountId = session.status === 'authenticated' ? session.account.accountId : null;
  const currentAccount = useRef(accountId); currentAccount.current = accountId;
  const queryClient = useQueryClient();
  const wallet = useWallet(accountId);
  useAccountSync(accountId);
  const banner = useQuery({ queryKey: ['banner'], enabled: Boolean(accountId), queryFn: async () => {
    const response = await apiGet('/api/banner', bannerResponse);
    if (response.error) throw new Error(response.error.message);
    return response.data;
  } });
  const [pending, setPending] = useState<PullRequest | null>(null);
  const [receipt, setReceipt] = useState<PullReceipt | null>(null);
  const [working, setWorking] = useState(false);
  const [storageProblem, setStorageProblem] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const inFlight = useRef(false);

  const submit = useCallback(async (owner: string, input: PullRequest, recover: boolean) => {
    if (inFlight.current) return;
    inFlight.current = true; setWorking(true); setMessage(null);
    try {
      let response = recover ? await apiGet(`/api/pulls/${input.requestId}`, receiptResponse) : null;
      if (!response || response.error?.code === 'NOT_FOUND') response = await economyMutation('/api/pulls', 'POST', input, receiptResponse);
      if (currentAccount.current !== owner) return;
      if (response.data) {
        setReceipt(response.data);
        void queryClient.invalidateQueries({ queryKey: ['wallet', owner] });
        void queryClient.invalidateQueries({ queryKey: ['collection', owner] });
      } else {
        setMessage(response.error.message);
        if (definitive.has(response.error.code)) {
          try { clearPendingPull(owner); setPending(null); } catch { setStorageProblem(true); }
          if (response.error.code === 'STALE_BANNER') void banner.refetch();
        }
        if (response.error.code === 'UNAUTHENTICATED') void refresh();
      }
    } finally {
      inFlight.current = false;
      if (currentAccount.current === owner) setWorking(false);
    }
  }, [queryClient, refresh, banner.refetch]);

  useEffect(() => {
    setPending(null); setReceipt(null); setWorking(false); setMessage(null); setStorageProblem(false);
    if (!accountId) return;
    try {
      const saved = readPendingPull(accountId);
      if (saved) { setPending(saved); void submit(accountId, saved, true); }
    } catch { setStorageProblem(true); }
    // A pending identity is recovered only on account entry, never regenerated by render/refetch.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [accountId]);

  const buy = (count: 1 | 10) => {
    if (!accountId || !banner.data || pending || inFlight.current || storageProblem) return;
    const input: PullRequest = { requestId: crypto.randomUUID(), bannerVersion: banner.data.version, count };
    try { savePendingPull(accountId, input); } catch { setStorageProblem(true); return; }
    setPending(input); void submit(accountId, input, false);
  };
  const finish = () => {
    if (!accountId || !receipt) return;
    try { clearPendingPull(accountId); setPending(null); setReceipt(null); setMessage(null); }
    catch { setStorageProblem(true); }
  };
  return <SessionBoundary><section className="collection-page" aria-label="Cosmetic invitations">
    <header className="page-heading"><div><h1>Invitations</h1><p>Invite a celestial companion to your collection.</p></div></header>
    {storageProblem ? <p role="alert" className="collection-notice">This tab cannot safely save or read an invitation. Enable session storage and reload before opening another. Existing unresolved data is preserved.</p> : null}
    {message ? <p role="alert" className="collection-notice">{message}</p> : null}
    {receipt ? <PullReveal key={receipt.requestId} receipt={receipt} onContinue={finish} /> : pending ? <section className="invitation-purchase" aria-live="polite">
      <h2>{working ? 'Confirming your invitation…' : 'Recover your invitation'}</h2>
      <p>Keep this request while the result is uncertain. Retrying uses the same invitation and cannot charge it twice.</p>
      <button className="secondary-button" type="button" disabled={working} onClick={() => accountId && void submit(accountId, pending, true)}>Recover existing invitation</button>
    </section> : banner.data ? <section className="invitation-purchase">
      <div><h2>{banner.data.name}</h2><p>{wallet.data ? `${wallet.data.balance} tickets available` : 'Loading your ticket balance…'}</p>
        <p>Earn tickets through qualifying poker hands. Cosmetics change appearance only.</p></div>
      <div className="collection-actions"><button className="primary-button" type="button" disabled={working || storageProblem || !wallet.data || wallet.data.balance < banner.data.prices.single} onClick={() => buy(1)}>Open 1 — {banner.data.prices.single} tickets</button>
        <button className="secondary-button" type="button" disabled={working || storageProblem || !wallet.data || wallet.data.balance < banner.data.prices.ten} onClick={() => buy(10)}>Open 10 — {banner.data.prices.ten} tickets</button></div>
      {wallet.data && wallet.data.balance < banner.data.prices.single ? <p>Not enough tickets yet. Play qualifying poker hands to earn your next invitation.</p> : null}
      {wallet.error ? <p role="alert">Ticket balance unavailable. <button type="button" onClick={() => void wallet.refetch()}>Retry balance</button></p> : null}
      <details><summary>Rates &amp; guarantees</summary><p>R {banner.data.weights.R}% · SR {banner.data.weights.SR}% · SSR {banner.data.weights.SSR}%.</p>
        <p>SR or better by the {banner.data.guarantees.sr}th pull without SR+. SSR by the {banner.data.guarantees.ssr}th pull without SSR. Ten invitations follow the same ordered rules.</p>
        <p>The SR guarantee keeps the base SSR chance. SSR takes priority and resets both counters; SR resets only the SR+ counter.</p>
        <p>Unowned SSR items are selected first until you own every SSR. Items are equally likely within the eligible rarity pool. Duplicates grant no new item and no ticket refund.</p></details>
      <p className="duplicate-disclosure">Duplicates give no additional item or refund. Your result is saved before its reveal.</p>
    </section> : <p role="status">{banner.error ? 'The catalogue is unavailable.' : 'Loading the catalogue…'} {banner.error ? <button type="button" onClick={() => void banner.refetch()}>Retry catalogue</button> : null}</p>}
    {banner.data ? <section className="catalogue-preview"><h2>The celestial catalogue</h2><p>Six avatars and six card backs. Free defaults are always available in Collection.</p>
      <ul className="cosmetic-grid">{banner.data.items.map((item) => <li className="cosmetic-item" key={item.id}>
        <img src={item.assetUrl} alt="" width="160" height="160" loading="lazy" /><span className={`rarity rarity--${item.rarity.toLowerCase()}`}>{item.rarity}</span>
        <h3>{item.name}</h3><p>{item.slot === 'avatar' ? 'Avatar' : 'Card back'}</p></li>)}</ul></section> : null}
  </section></SessionBoundary>;
}
