import { isBackendPath, proxyBackend, type BackendEnv } from './proxy';

// @ts-ignore Generated by the OpenNext build before Wrangler bundles this entrypoint.
import nextWorker from '../.open-next/worker.js';

type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
};

type NextWorker = {
  fetch(request: Request, env: BackendEnv, context: WorkerContext): Promise<Response>;
};

export default {
  async fetch(request: Request, env: BackendEnv, context: WorkerContext): Promise<Response> {
    if (isBackendPath(new URL(request.url).pathname)) return proxyBackend(request, env);
    return (nextWorker as NextWorker).fetch(request, env, context);
  },
};
