import { routeWorkerRequest, type BackendEnv } from './proxy';

// @ts-ignore Generated by the OpenNext build before Wrangler bundles this entrypoint.
import nextWorker from '../.open-next/worker.js';

type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
};

type NextWorker = {
  fetch(request: Request, env: BackendEnv, context: WorkerContext): Promise<Response>;
};

export default {
  async fetch(request: Request, env: BackendEnv, context: WorkerContext): Promise<Response> {
    return routeWorkerRequest(
      request,
      env,
      (frontendRequest) => (nextWorker as NextWorker).fetch(frontendRequest, env, context),
    );
  },
};
